[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"
outputDirectory = "dist"

[deploy]
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"
healthcheckPath = "/novara-mvp/"
healthcheckTimeout = 300

[environment]
NODE_ENV = "production"
PORT = "$PORT" 