[build]
builder = "NIXPACKS"
buildCommand = "npm install --omit=dev"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environment]
NODE_ENV = "production"
PORT = "$PORT" 