[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environment]
USE_LOCAL_DATABASE = "false"
DATABASE_TYPE = "airtable" 